apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pages
    tier: database
  name: mysql
  namespace: edgware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pages
      tier: database
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pages
        tier: database
    spec:
      volumes:
      - name: mysql-persistent-storage
        emptyDir: {}
      containers:
      - image: mysql:8.0
        name: mysql
        resources: {}
        env:
          - name: MYSQL_SERVICE_HOST
            value: "pages-mysql"
          - name: MYSQL_SERVICE_PORT
            value: "3306"
          - name: MYSQL_DATABASE
            value: "pages"
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /docker-entrypoint-initdb.d
status: {}

